'use client';
import React,{useEffect,useState}from'react';
import Link from'next/link';
import{useRouter}from'next/navigation';
import{Search,UserPlus,LogOut,ArrowUpRight,AlertCircle,CheckCircle2,Clapperboard}from'lucide-react';
import{useAuth}from'@/context/AuthContext';
import{supabase}from'@/lib/supabase';
interface ClientRow{project_id:string;email:string;display_name:string;company_name:string;status:string;latestCut:string}
export default function EditorPage(){
 const router=useRouter();const{currentUser,isLoading,logout}=useAuth();const[clients,setClients]=useState<ClientRow[]>([]);const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[showForm,setShowForm]=useState(false);const[details,setDetails]=useState({name:'',companyName:'',email:'',password:''});const[msg,setMsg]=useState<{error:boolean;text:string}|null>(null);const[saving,setSaving]=useState(false);
 const loadClients=async()=>{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)return;try{const r=await fetch('/api/editor/clients',{headers:{Authorization:`Bearer ${token}`}});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not load clients.');setClients(x.clients??[])}catch(e){setMsg({error:true,text:e instanceof Error?e.message:'Could not load clients.'})}finally{setLoading(false)}};
 useEffect(()=>{if(!isLoading&&(!currentUser||currentUser.role!=='Editor'))router.replace('/editor/login');if(currentUser?.role==='Editor')void loadClients()},[currentUser,isLoading,router]);
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setMsg(null);try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Your session expired. Sign in again.');const r=await fetch('/api/editor/clients',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(details)});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not create client.');setDetails({name:'',companyName:'',email:'',password:''});setMsg({error:false,text:`Client account created for ${x.email}.`});await loadClients()}catch(e){setMsg({error:true,text:e instanceof Error?e.message:'Could not create client.'})}finally{setSaving(false)}};
 if(isLoading||!currentUser||currentUser.role!=='Editor')return <div className="min-h-screen flex items-center justify-center bg-neutral-950"><div className="h-6 w-6 animate-spin rounded-full border-2 border-indigo-600 border-t-transparent"/></div>;
 const filtered=clients.filter(c=>[c.display_name,c.company_name,c.email].some(v=>v.toLowerCase().includes(query.toLowerCase())));
 return <main className="min-h-screen bg-neutral-100 p-4 text-neutral-900 dark:bg-neutral-950 dark:text-neutral-100 sm:p-8"><div className="mx-auto max-w-6xl space-y-7">
 <header className="flex flex-wrap items-center justify-between gap-4 border-b border-neutral-200 pb-5 dark:border-neutral-800"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-600 text-white"><Clapperboard size={21}/></div><div><p className="text-xs font-semibold uppercase tracking-wide text-indigo-500">SyncCut · Editor</p><h1 className="text-2xl font-bold">Client projects</h1></div></div><div className="flex items-center gap-2"><span className="hidden text-sm text-neutral-500 sm:inline">Signed in as {currentUser.name}</span><button onClick={()=>{logout();router.push('/editor/login')}} className="inline-flex items-center gap-2 rounded-xl border border-neutral-200 bg-white px-3 py-2 text-sm dark:border-neutral-800 dark:bg-neutral-900"><LogOut size={15}/>Sign out</button></div></header>
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Choose a client workspace</h2><p className="mt-1 text-sm text-neutral-500">Each client’s videos, notes, and project details stay in their own workspace.</p></div><button onClick={()=>{setShowForm(!showForm);setMsg(null)}} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><UserPlus size={16}/>Add client</button></div>
 {showForm&&<section className="rounded-2xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900"><h3 className="font-semibold">Create a client login</h3><p className="mb-4 mt-1 text-sm text-neutral-500">The account is created as verified. Share the password with the client securely.</p><form onSubmit={create} className="grid gap-3 sm:grid-cols-2">
 <input aria-label="Client name" placeholder="Client name" value={details.name} onChange={e=>setDetails({...details,name:e.target.value})} required minLength={2} className="rounded-xl border border-neutral-300 bg-neutral-50 px-3 py-2.5 text-sm dark:border-neutral-700 dark:bg-neutral-950"/>
 <input aria-label="Company name" placeholder="Company name" value={details.companyName} onChange={e=>setDetails({...details,companyName:e.target.value})} required minLength={2} className="rounded-xl border border-neutral-300 bg-neutral-50 px-3 py-2.5 text-sm dark:border-neutral-700 dark:bg-neutral-950"/>
 <input aria-label="Client email" type="email" placeholder="Client email" value={details.email} onChange={e=>setDetails({...details,email:e.target.value})} required className="rounded-xl border border-neutral-300 bg-neutral-50 px-3 py-2.5 text-sm dark:border-neutral-700 dark:bg-neutral-950"/>
 <input aria-label="Temporary password" type="password" placeholder="Temporary password (12+ characters)" value={details.password} onChange={e=>setDetails({...details,password:e.target.value})} required minLength={12} autoComplete="new-password" className="rounded-xl border border-neutral-300 bg-neutral-50 px-3 py-2.5 text-sm dark:border-neutral-700 dark:bg-neutral-950"/>
 <button disabled={saving} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60 sm:col-span-2">{saving?'Creating…':'Create client account'}</button></form>{msg&&<p role="status" className={`mt-3 flex items-center gap-2 text-sm ${msg.error?'text-rose-600':'text-emerald-600'}`}>{msg.error?<AlertCircle size={16}/>:<CheckCircle2 size={16}/>} {msg.text}</p>}</section>}
 {msg?.error&&!showForm&&<p role="alert" className="text-sm text-rose-600">{msg.text}</p>}
 <label className="flex max-w-lg items-center gap-2 rounded-xl border border-neutral-200 bg-white px-3 dark:border-neutral-800 dark:bg-neutral-900"><Search size={17} className="text-neutral-400"/><input aria-label="Search clients" placeholder="Search by name, company, or email" value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent py-3 text-sm outline-none"/></label>
 {loading?<div className="py-16 text-center text-sm text-neutral-500">Loading client projects…</div>:filtered.length===0?<div className="rounded-2xl border border-dashed border-neutral-300 py-16 text-center dark:border-neutral-700"><h3 className="font-semibold">{clients.length?'No matching clients':'No client projects yet'}</h3><p className="mt-1 text-sm text-neutral-500">{clients.length?'Try another search.':'Add a client account to create their workspace.'}</p></div>:<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><Link key={c.project_id} href={`/editor/clients/${encodeURIComponent(c.project_id)}`} className="group rounded-2xl border border-neutral-200 bg-white p-5 transition hover:border-indigo-400 hover:shadow-md dark:border-neutral-800 dark:bg-neutral-900"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-neutral-500">{c.company_name}</p><h3 className="mt-1 text-lg font-semibold">{c.display_name}</h3><p className="mt-1 break-all text-sm text-neutral-500">{c.email}</p></div><ArrowUpRight size={18} className="text-neutral-400 group-hover:text-indigo-500"/></div><div className="mt-5 flex items-center justify-between border-t border-neutral-100 pt-4 text-sm dark:border-neutral-800"><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs dark:bg-neutral-800">{c.status}</span><span className="max-w-[55%] truncate text-neutral-500">{c.latestCut}</span></div></Link>)}</section>}
 </div></main>
}
