'use client';
import React,{useState}from'react';
import Link from'next/link';
import{Project,CreativeBrief,Deliverable,ProjectStatus,ActionRequiredBy,FeedbackNote}from'@/types';
import{useAuth}from'@/context/AuthContext';
import{useRouter}from'next/navigation';
import{TopBar}from'./TopBar';import{ScriptBox}from'./ScriptBox';import{VisualReferences}from'./VisualReferences';import{ActionAlert}from'./ActionAlert';import{VideoPlayer}from'./VideoPlayer';import{FeedbackSection}from'./FeedbackSection';import{EditorToolbar}from'./EditorToolbar';import{ClientPortal}from'./ClientPortal';
import{Clapperboard,LogOut,Shield,Eye,X,ArrowLeft}from'lucide-react';
interface Props{project:Project;brief:CreativeBrief;deliverable:Deliverable;isStatusSaving?:boolean;onStatusChange:(s:ProjectStatus)=>void;onPostNewCut:(c:{version:string;videoUrl:string;duration:number})=>void;onSetActionAlert:(a:ActionRequiredBy,t:string)=>void;onUpdateScript:(b:CreativeBrief)=>void;onAddNote:(n:Omit<FeedbackNote,'id'|'created_at'>)=>void|Promise<void>;onApproveCut:()=>void;onUploadSuccess:(f:string)=>void}
export const EditorDashboard:React.FC<Props>=({project,brief,deliverable,isStatusSaving=false,onStatusChange,onPostNewCut,onSetActionAlert,onUpdateScript,onAddNote,onApproveCut,onUploadSuccess})=>{
 const router=useRouter();const{currentUser,logout}=useAuth();const[tc,setTc]=useState('');const[preview,setPreview]=useState(false);
 return <div className="min-h-screen bg-neutral-100 p-4 text-neutral-900 dark:bg-neutral-950 dark:text-neutral-100 sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
 <header className="flex flex-wrap items-center justify-between gap-4 border-b border-neutral-200 pb-4 dark:border-neutral-800"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-600 font-bold text-white"><Clapperboard className="h-5 w-5"/></div><div><div className="flex items-center gap-2"><span className="rounded border border-indigo-200 bg-indigo-50 px-2 py-0.5 text-[10px] font-black uppercase tracking-wider text-indigo-500 dark:border-indigo-800/50 dark:bg-indigo-950/60">Editor</span><span className="text-xs text-neutral-400">Client workspace</span></div><div className="mt-0.5 text-sm font-semibold">{project.title}</div></div></div>
 <div className="flex flex-wrap items-center gap-2"><Link href="/editor" className="inline-flex items-center gap-1.5 rounded-xl border border-neutral-200 bg-white px-3 py-2 text-xs font-semibold dark:border-neutral-800 dark:bg-neutral-900"><ArrowLeft size={14}/>All clients</Link><span className="hidden items-center gap-1.5 rounded-xl border border-neutral-200 bg-white px-3 py-2 text-xs dark:border-neutral-800 dark:bg-neutral-900 sm:flex"><Shield className="h-3.5 w-3.5 text-indigo-500"/>Signed in as <strong>{currentUser?.name}</strong></span><button onClick={()=>setPreview(true)} className="inline-flex items-center gap-1.5 rounded-xl border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-600 dark:border-indigo-800 dark:bg-indigo-950/50 dark:text-indigo-400"><Eye size={14}/>Preview client portal</button><button onClick={()=>{logout();router.push('/editor/login')}} className="inline-flex items-center gap-1.5 rounded-xl border border-neutral-200 bg-white px-3 py-2 text-xs dark:border-neutral-800 dark:bg-neutral-900"><LogOut size={14}/>Sign out</button></div></header>
 <EditorToolbar deliverable={deliverable} brief={brief} onPostNewCut={onPostNewCut} onSetActionAlert={onSetActionAlert} onUpdateScript={onUpdateScript}/><TopBar project={project} onStatusChange={onStatusChange} isStatusSaving={isStatusSaving}/>
 <main className="grid grid-cols-1 items-start gap-6 lg:grid-cols-12"><section className="space-y-6 lg:col-span-6"><ScriptBox brief={brief}/><VisualReferences references={brief.references}/></section><section className="space-y-6 lg:col-span-6"><ActionAlert deliverable={deliverable} onUploadSuccess={onUploadSuccess}/><VideoPlayer deliverable={deliverable} onTimecodeSelected={setTc} onApproveCut={onApproveCut}/><FeedbackSection notes={deliverable.feedback_notes} currentTimecode={tc} onAddNote={onAddNote}/></section></main>
 {preview&&<div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-black/80 p-4 backdrop-blur-sm"><div className="w-full max-w-6xl overflow-hidden rounded-2xl border border-neutral-700 bg-neutral-100 shadow-2xl dark:bg-neutral-950"><div className="flex items-center justify-between border-b border-neutral-800 bg-neutral-900 p-4 text-white"><div className="flex items-center gap-2"><Eye className="h-4 w-4 text-emerald-400"/><span className="text-xs font-bold uppercase tracking-wider text-neutral-300">Client preview</span></div><button onClick={()=>setPreview(false)} className="rounded-lg bg-neutral-800 p-1.5 text-neutral-300 hover:text-white"><X className="h-4 w-4"/></button></div><div className="max-h-[85vh] overflow-y-auto p-4 sm:p-6"><ClientPortal project={project} brief={brief} deliverable={deliverable} onAddNote={onAddNote} onApproveCut={onApproveCut} onUploadSuccess={onUploadSuccess}/></div></div></div>}
 </div></div>
};
