'use client';
import React,{createContext,useContext,useState,useEffect}from'react';
import{Project,CreativeBrief,Deliverable,ProjectStatus,ActionRequiredBy,FeedbackNote}from'@/types';
import{mockProject,mockBrief,mockDeliverable}from'@/lib/mock-data';
import{isSupabaseConfigured,supabase}from'@/lib/supabase';
import{useAuth}from'@/context/AuthContext';
interface Ctx{project:Project;brief:CreativeBrief;deliverable:Deliverable;isProjectLoaded:boolean;updateStatus:(s:ProjectStatus)=>void;postNewCut:(c:{version:string;videoUrl:string;duration:number})=>void;setActionAlert:(a:ActionRequiredBy,t:string)=>void;updateScript:(b:CreativeBrief)=>void;addNote:(n:Omit<FeedbackNote,'id'|'created_at'>)=>void;approveCut:()=>void;uploadSuccess:(f:string)=>void}
const Context=createContext<Ctx|undefined>(undefined);interface State{project:Project;brief:CreativeBrief;deliverable:Deliverable}
const clean=(d:Deliverable)=>({...d,video_url:d.video_url?.includes('sample-cut-guid')?'':d.video_url,feedback_notes:(d.feedback_notes??[]).filter(n=>n.id!=='note_1')});
function initial(id:string,u:ReturnType<typeof useAuth>['currentUser']):State{return{project:{...mockProject,project_id:id,client_id:u?.user_id??mockProject.client_id,title:u?.company_name?`Project: ${u.company_name}`:mockProject.title},brief:{...mockBrief,brief_id:`brief_${id}`,project_id:id,script_scenes:mockBrief.script_scenes.map(s=>({...s})),references:mockBrief.references.map(r=>({...r}))},deliverable:{...mockDeliverable,deliverable_id:`deliverable_${id}`,project_id:id,video_url:'',feedback_notes:[],uploaded_at:'No video uploaded yet'}}}
export const ProjectProvider:React.FC<{children:React.ReactNode;projectId?:string}>=({children,projectId:propId})=>{
 const{currentUser}=useAuth();const id=propId??currentUser?.project_id??mockProject.project_id;const uid=currentUser?.user_id;const remote=isSupabaseConfigured&&Boolean(uid)&&Boolean(propId??currentUser?.project_id)&&!uid?.startsWith('usr_');
 const[project,setProject]=useState(()=>initial(id,currentUser).project);const[brief,setBrief]=useState(()=>initial(id,currentUser).brief);const[deliverable,setDeliverable]=useState(()=>initial(id,currentUser).deliverable);const[ready,setReady]=useState<string|null>(null);
 useEffect(()=>{let cancelled=false;const seed=initial(id,currentUser);setReady(null);const restore=async()=>{if(!remote){setProject(seed.project);setBrief(seed.brief);setDeliverable(seed.deliverable);setReady(id);return}try{const{data,error}=await supabase.from('project_portal_state').select('state').eq('project_id',id).maybeSingle();if(error)throw error;if(cancelled)return;setProject(data?.state?.project??seed.project);setBrief(data?.state?.brief??seed.brief);setDeliverable(data?.state?.deliverable?clean(data.state.deliverable as Deliverable):seed.deliverable);setReady(id)}catch(e){console.error('Failed to restore project state from Supabase.',e)}};void restore();return()=>{cancelled=true}},[id,uid,currentUser?.company_name,remote]);
 useEffect(()=>{if(ready!==id||!remote||!uid)return;void supabase.from('project_portal_state').upsert({project_id:id,state:{project,brief,deliverable},updated_by:uid},{onConflict:'project_id'}).then(({error})=>{if(error)console.error('Failed to save project state to Supabase.',error)})},[project,brief,deliverable,ready,id,remote,uid]);
 useEffect(()=>{if(!remote||ready!==id)return;const ch=supabase.channel(`portal-${id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'project_portal_state',filter:`project_id=eq.${id}`},p=>{const s=(p.new as{state?:Partial<State>}).state;if(s?.project)setProject(s.project);if(s?.brief)setBrief(s.brief);if(s?.deliverable)setDeliverable(clean(s.deliverable))}).subscribe();return()=>{void supabase.removeChannel(ch)}},[id,remote,ready]);
 const updateStatus=(status:ProjectStatus)=>setProject(p=>({...p,status}));
 const postNewCut=(c:{version:string;videoUrl:string;duration:number})=>{setDeliverable(d=>({...d,version_number:c.version,video_url:c.videoUrl,duration_seconds:c.duration,uploaded_at:'Just now by Editor',approval_status:'Pending',action_required_by:'Client',action_banner_text:`Review ${c.version} and leave your notes below`}));if(['Scripting','Pre-Production','Shooting'].includes(project.status))setProject(p=>({...p,status:'Editing'}))};
 const setActionAlert=(actionBy:ActionRequiredBy,text:string)=>setDeliverable(d=>({...d,action_required_by:actionBy,action_banner_text:text}));
 const updateScript=(updated:CreativeBrief)=>setBrief(updated);
 const addNote=(n:Omit<FeedbackNote,'id'|'created_at'>)=>{const note:FeedbackNote={...n,id:`note_${Date.now()}`,created_at:new Date().toISOString()};setDeliverable(d=>({...d,feedback_notes:[note,...d.feedback_notes]}))};
 const uploadSuccess=(f:string)=>setDeliverable(d=>({...d,action_required_by:'None',action_banner_text:`Asset received (${f}). Ball is in Editor's court.`}));
 const approveCut=()=>{setDeliverable(d=>({...d,approval_status:'Approved',action_required_by:'None'}));setProject(p=>({...p,status:'Final Review'}))};
 return <Context.Provider value={{project,brief,deliverable,isProjectLoaded:ready===id,updateStatus,postNewCut,setActionAlert,updateScript,addNote,approveCut,uploadSuccess}}>{children}</Context.Provider>
};
export const useProject=()=>{const c=useContext(Context);if(!c)throw new Error('useProject must be used within a ProjectProvider');return c};
